#!/bin/sh
#SBATCH --mem=72g
#SBATCH --cpus-per-task=24
#SBATCH --gres=lscratch:24
#SBATCH --time=10-00:00:00
#SBATCH --job-name iqtree_phyluce_hydroidolina
#SBATCH --mail-type BEGIN,END,FAIL,TIME_LIMIT_80

# create variable for source and target directories
prodir="/data/NHGRIBaxevanis/connellym2/projects/hydractiniidae_popgen"

module load iqtree

set=$1 # eg. phyluce_test_3
pct=$2 # eg. 75 or 50

iqtree2 \
-s ${prodir}/outputs/phyluce/uce-taxon-sets/${set}/${set}-mafft-nexus-internal-trimmed-gblocks-clean-${pct}p-raxml/${set}-mafft-nexus-internal-trimmed-gblocks-clean-${pct}p-raxml.phylip \
-p ${prodir}/outputs/phyluce/uce-taxon-sets/${set}/${set}-mafft-nexus-internal-trimmed-gblocks-clean-${pct}p-raxml/${set}-mafft-nexus-internal-trimmed-gblocks-clean-${pct}p-raxml.partitions \
--seqtype DNA \
-m MFP \
-bb 1000 \
-alrt 1000 \
-nt $SLURM_CPUS_PER_TASK \
--prefix ${prodir}/outputs/iqtree/iqtree_${set}_${pct}p

echo = `date` job $JOB_NAME done