#!/bin/sh
#SBATCH --mem=192g
#SBATCH --cpus-per-task=16
#SBATCH --gres=lscratch:24
#SBATCH --time=2-00:00:00
#SBATCH --job-name pcangsd_hydractinia
#SBATCH --mail-type BEGIN,END,FAIL,TIME_LIMIT_80

# create variable for source and target directories
prodir="/data/NHGRIBaxevanis/connellym2/projects/hydractiniidae_popgen"

# specify sample set
set=$1 # ex. midatlantic

# conda activate pcangsd

pcangsd \
--beagle ${prodir}/outputs/angsd/${set}/${set}_ibs05.beagle.gz \
-o ${prodir}/outputs/angsd/${set}/${set}_ibs05 \
--admix \
--threads $SLURM_CPUS_PER_TASK

# Outputs the following files:
# log-file (pcangsd.log)
# covariance matrix (pcangsd.cov)
# admixture proportions (pcangsd.admix.3.Q)

echo = `date` job $JOB_NAME done